version: '3'

services:
  blog:
    build: status-blog
    depends_on:
      - api
      - cache
    ports:
      - 80:3000
    environment:
      REDIS_URI: redis://cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m
      timeout: 10s
      retries: 3
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  api:
    build: user-api
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m
      timeout: 10s
      retries: 3
    logging:
      options:
        max-size: "10m"
        max-file: "3"


  cache:
    image: redis:latest
    ports:
      - 6379:6379
