version: '3'

services:
  blog:
    build: status-blog
    depends_on:
      - api
    ports:
      - 80:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m
      timeout: 10s
      retries: 3
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  api:
    build: user-api
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m
      timeout: 10s
      retries: 3
    logging:
      options:
        max-size: "10m"
        max-file: "3"


